#!/bin/bash

echo "=== CRIANDO VERSÃO PNG DA IMAGEM 586 ==="
echo ""
echo "Execute este comando como root ou com sudo:"
echo ""
echo "sudo apt update && sudo apt install -y librsvg2-bin"
echo ""
echo "Depois execute:"
echo "rsvg-convert -w 1920 -h 1080 public/images/banners/586.svg -o public/images/banners/586.png"
echo ""
echo "Ou simplesmente execute:"
echo "./convert_svg_png.sh"
echo ""
echo "=== INSTRUÇÕES ==="
echo "1. Execute o script com privilégios de administrador"
echo "2. O script irá instalar o conversor e criar o arquivo PNG"
echo "3. Atualize o CSS para usar '586.png' em vez de '586.svg'"
echo ""
echo "Arquivo atual: public/images/banners/586.svg"
echo "Dimensões: 3800x2000px (mesmas do original)"
echo "Formato: SVG vetorial escalável"
